name: Deploy Next.js Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy build (.next) to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.87.106.40.188 }}
          username: ${{ secrets.root }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: ".next/**"
          target: "/var/www/TML-Website/"

      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.87.106.40.188 }}
          username: ${{ secrets.root }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /var/www/TML-Website
            pm2 restart server.js
